gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl_update: true
    cookie:
        enabled: true
        same_site: '%jwt_samesite%'
        path: /
        domain: '%jwt_domain%'
        http_only: true
        secure: '%jwt_secure%'
        partitioned: false
        remove_token_from_body: true